plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "justfile"
  - "*.all.md"
  - "*.all.json"

title: "Esperanto Shavian"
lang: "en"
baseurl: "/shaw-eo"
repository: "salif/shaw-eo"

author:
  name: "Salif Mehmed"
  url: "https://salif.eu"

defaults:
  - scope:
      path: "README.eo_shaw.md"
    values:
      lang: "eo-Shaw"
      description: "ğ‘¢ğ‘§ğ‘µ ğ‘«ğ‘¦ğ‘¨ ğ‘ğ‘®ğ‘©ğ‘ğ‘© ğ‘“ğ‘¨ğ‘®ğ‘¦ ğ‘’ğ‘¤ğ‘¨ğ‘ğ‘¨ğ‘®ğ‘¨ğ‘µ ğ‘¨ğ‘®ğ‘¨ğ‘µğ‘¡ğ‘©ğ‘¢ğ‘µ ğ‘šğ‘¨ğ‘Ÿğ‘¦ğ‘‘ğ‘¨ğ‘¢ğ‘µ ğ‘•ğ‘ªğ‘® QWERTY ğ‘’ğ‘¨ğ‘¢ Colemak, ğ‘¨ğ‘›ğ‘¨ğ‘ğ‘‘ğ‘¦ğ‘‘ğ‘¨ğ‘¢ğ‘µ ğ‘ğ‘©ğ‘® ğ‘¤ğ‘¨ ğ‘§ğ‘•ğ‘ğ‘§ğ‘®ğ‘¨ğ‘µğ‘‘ğ‘¨ ğ‘–ğ‘¨ğ‘ğ‘¨ ğ‘¨ğ‘¤ğ‘“ğ‘¨ğ‘šğ‘§ğ‘‘ğ‘©."
      image: "./media/preview_qwerty.png"
  - scope:
      path: "LINUX.eo_shaw.md"
    values:
      lang: "eo-Shaw"
      description: "ğ‘•ğ‘§ğ‘’ğ‘ğ‘ª ğ‘—ğ‘¦ ğ‘‘ğ‘¦ğ‘ªğ‘¢ğ‘µ ğ‘¦ğ‘µğ‘•ğ‘‘ğ‘®ğ‘ªğ‘’ğ‘”ğ‘¦ğ‘©ğ‘¢ğ‘µ"
  - scope:
      path: "README.eo.md"
    values:
      lang: "eo"
      description: "Jen mia provo fari klavaran aranÄojn bazitajn sur QWERTY kaj Colemak, adaptitajn por la Esperanta Åœava alfabeto"
      image: "./media/preview_qwerty.png"
  - scope:
      path: "README.zh-CN.md"
    values:
      lang: "zh-CN"
      description: "è¿™æ˜¯æˆ‘å°è¯•åˆ¶ä½œåŸºäº QWERTY å’Œ Colemak çš„é”®ç›˜å¸ƒå±€ï¼Œå¹¶é€‚åº”ä¸–ç•Œè¯­ Shavian å­—æ¯è¡¨"
      image: "./media/preview_qwerty.png"
  - scope:
      path: "README.es.md"
    values:
      lang: "es"
      description: "Este es mi intento de crear diseÃ±os de teclado basados â€‹â€‹en QWERTY y Colemak, adaptados al alfabeto esperanto Shavian"
      image: "./media/preview_qwerty.png"
  - scope:
      path: "README.ar.md"
    values:
      lang: "ar"
      description: "Ù‡Ø°Ù‡ Ù‡ÙŠ Ù…Ø­Ø§ÙˆÙ„ØªÙŠ Ù„Ø¥Ù†Ø´Ø§Ø¡ ØªØ®Ø·ÙŠØ·Ø§Øª Ù„Ù„ÙˆØ­Ø© Ø§Ù„Ù…ÙØ§ØªÙŠØ­ ØªØ¹ØªÙ…Ø¯ Ø¹Ù„Ù‰ QWERTY ÙˆColemakØŒ Ù…Ø¹ ØªÙƒÙŠÙŠÙÙ‡Ø§ Ù…Ø¹ Ø£Ø¨Ø¬Ø¯ÙŠØ© Ø§Ù„Ø¥Ø³Ø¨Ø±Ø§Ù†ØªÙˆ Ø§Ù„Ø´Ø§ÙÙŠØ§Ù†ÙŠØ©"
      image: "./media/preview_qwerty.png"
  - scope:
      path: "README.pt.md"
    values:
      lang: "pt"
      description: "Esta Ã© minha tentativa de fazer layouts de teclado baseados em QWERTY e Colemak, adaptados para o alfabeto Esperanto Shavian"
      image: "./media/preview_qwerty.png"
  - scope:
      path: "README.ru.md"
    values:
      lang: "ru"
      description: "Ğ­Ñ‚Ğ¾ Ğ¼Ğ¾Ñ Ğ¿Ğ¾Ğ¿Ñ‹Ñ‚ĞºĞ° ÑĞ´ĞµĞ»Ğ°Ñ‚ÑŒ Ñ€Ğ°ÑĞºĞ»Ğ°Ğ´ĞºĞ¸ ĞºĞ»Ğ°Ğ²Ğ¸Ğ°Ñ‚ÑƒÑ€Ñ‹ Ğ½Ğ° Ğ¾ÑĞ½Ğ¾Ğ²Ğµ QWERTY Ğ¸ Colemak, Ğ°Ğ´Ğ°Ğ¿Ñ‚Ğ¸Ñ€Ğ¾Ğ²Ğ°Ğ½Ğ½Ñ‹Ğµ Ğ¿Ğ¾Ğ´ ÑÑĞ¿ĞµÑ€Ğ°Ğ½Ñ‚Ğ¾-ÑˆĞ°Ğ²Ğ¸Ğ°Ğ½ÑĞºĞ¸Ğ¹ Ğ°Ğ»Ñ„Ğ°Ğ²Ğ¸Ñ‚"
      image: "./media/preview_qwerty.png"
  - scope:
      path: "README.id.md"
    values:
      lang: "id"
      description: "Ini adalah upaya saya membuat layout keyboard berdasarkan QWERTY dan Colemak, yang diadaptasi untuk alfabet Esperanto Shavian"
      image: "./media/preview_qwerty.png"
  - scope:
      path: "README.tr.md"
    values:
      lang: "tr"
      description: "Bu, Esperanto Åavi alfabesine uyarlanmÄ±ÅŸ, QWERTY ve Colemak'Ä± temel alan klavye dÃ¼zenleri yapma giriÅŸimimdir"
      image: "./media/preview_qwerty.png"
  - scope:
      path: "README.bg.md"
    values:
      lang: "bg"
      description: "Ğ¢Ğ¾Ğ²Ğ° Ğµ Ğ¼Ğ¾ÑÑ‚ Ğ¾Ğ¿Ğ¸Ñ‚ Ğ´Ğ° Ğ½Ğ°Ğ¿Ñ€Ğ°Ğ²Ñ ĞºĞ»Ğ°Ğ²Ğ¸Ğ°Ñ‚ÑƒÑ€Ğ½Ğ¸ Ğ¿Ğ¾Ğ´Ñ€ĞµĞ´Ğ±Ğ¸, Ğ±Ğ°Ğ·Ğ¸Ñ€Ğ°Ğ½Ğ¸ Ğ½Ğ° QWERTY Ğ¸ Colemak, Ğ°Ğ´Ğ°Ğ¿Ñ‚Ğ¸Ñ€Ğ°Ğ½Ğ¸ Ğ·Ğ° ĞµÑĞ¿ĞµÑ€Ğ°Ğ½Ñ‚ÑĞºĞ°Ñ‚Ğ° ÑˆĞ°Ğ²Ğ¸Ğ°Ğ½ÑĞºĞ° Ğ°Ğ·Ğ±ÑƒĞºĞ°"
      image: "./media/preview_qwerty.png"
  - scope:
      path: "README.md"
    values:
      lang: "en"
      description: "This is my attempt to make keyboard layouts based on QWERTY and Colemak, adapted for the Esperanto Shavian alphabet"
      image: "./media/preview_qwerty.png"
  - scope:
      path: "LINUX.eo.md"
    values:
      lang: "eo"
      description: "Sekvu Ä‰i tiujn instrukciojn"
  - scope:
      path: "LINUX.zh-CN.md"
    values:
      lang: "zh-CN"
      description: "è¯·éµå¾ªè¿™äº›è¯´æ˜"
  - scope:
      path: "LINUX.es.md"
    values:
      lang: "es"
      description: "Siga estas instrucciones"
  - scope:
      path: "LINUX.ar.md"
    values:
      lang: "ar"
      description: "Ø§ØªØ¨Ø¹ Ù‡Ø°Ù‡ Ø§Ù„ØªØ¹Ù„ÙŠÙ…Ø§Øª"
  - scope:
      path: "LINUX.pt.md"
    values:
      lang: "pt"
      description: "Siga estas instruÃ§Ãµes"
  - scope:
      path: "LINUX.ru.md"
    values:
      lang: "ru"
      description: "Ğ¡Ğ»ĞµĞ´ÑƒĞ¹Ñ‚Ğµ ÑÑ‚Ğ¸Ğ¼ Ğ¸Ğ½ÑÑ‚Ñ€ÑƒĞºÑ†Ğ¸ÑĞ¼"
  - scope:
      path: "LINUX.id.md"
    values:
      lang: "id"
      description: "Ikuti petunjuk ini"
  - scope:
      path: "LINUX.tr.md"
    values:
      lang: "tr"
      description: "Bu talimatlarÄ± izleyin"
  - scope:
      path: "LINUX.bg.md"
    values:
      lang: "bg"
      description: "Ğ¡Ğ»ĞµĞ´Ğ²Ğ°Ğ¹Ñ‚Ğµ Ñ‚ĞµĞ·Ğ¸ Ğ¸Ğ½ÑÑ‚Ñ€ÑƒĞºÑ†Ğ¸Ğ¸"
  - scope:
      path: "LINUX.md"
    values:
      lang: "en"
      description: "Follow these instructions"
