"bg":
  footer_os: "Ğ¢Ğ¾Ğ·Ğ¸ ÑĞ°Ğ¹Ñ‚ Ğµ Ñ Ğ¾Ñ‚Ğ²Ğ¾Ñ€ĞµĞ½ ĞºĞ¾Ğ´."
  footer_im: "ĞŸĞ¾Ğ´Ğ¾Ğ±Ñ€ĞµÑ‚Ğµ Ñ‚Ğ°Ğ·Ğ¸ ÑÑ‚Ñ€Ğ°Ğ½Ğ¸Ñ†Ğ°"
"eo":
  footer_os: "Äˆi tiu retejo estas malfermita fonto."
  footer_im: "Plibonigu Ä‰i tiun paÄon"
"eo-Shaw":
  footer_os: "ğ‘—ğ‘¦ ğ‘‘ğ‘¦ğ‘ª ğ‘®ğ‘§ğ‘‘ğ‘§ğ‘¢ğ‘© ğ‘§ğ‘•ğ‘‘ğ‘¨ğ‘• ğ‘«ğ‘¨ğ‘¤ğ‘“ğ‘§ğ‘®ğ‘«ğ‘¦ğ‘‘ğ‘¨ ğ‘“ğ‘©ğ‘µğ‘‘ğ‘©."
  footer_im: "ğ‘ğ‘¤ğ‘¦ğ‘šğ‘©ğ‘µğ‘¦ğ‘œğ‘ª ğ‘—ğ‘¦ ğ‘‘ğ‘¦ğ‘ªğ‘µ ğ‘ğ‘¨ğ‘¡ğ‘©ğ‘µ"
"tr":
  footer_os: "Bu site aÃ§Ä±k kaynaktÄ±r."
  footer_im: "Bu sayfayÄ± geliÅŸtirin"
"zh-CN":
  footer_os: "è¯¥ç½‘ç«™æ˜¯å¼€æºçš„ã€‚"
  footer_im: "æ”¹è¿›æ­¤é¡µé¢"
"es":
  footer_os: "Este sitio es de cÃ³digo abierto."
  footer_im: "Mejorar esta pÃ¡gina"
"ar":
  footer_os: "Ù‡Ø°Ø§ Ø§Ù„Ù…ÙˆÙ‚Ø¹ Ù…ÙØªÙˆØ­ Ø§Ù„Ù…ØµØ¯Ø±."
  footer_im: "ØªØ­Ø³ÙŠÙ† Ù‡Ø°Ù‡ Ø§Ù„ØµÙØ­Ø©"
"pt":
  footer_os: "Este site Ã© de cÃ³digo aberto."
  footer_im: "Melhorar esta pÃ¡gina"
"ru":
  footer_os: "Ğ­Ñ‚Ğ¾Ñ‚ ÑĞ°Ğ¹Ñ‚ Ñ Ğ¾Ñ‚ĞºÑ€Ñ‹Ñ‚Ñ‹Ğ¼ Ğ¸ÑÑ…Ğ¾Ğ´Ğ½Ñ‹Ğ¼ ĞºĞ¾Ğ´Ğ¾Ğ¼."
  footer_im: "Ğ£Ğ»ÑƒÑ‡ÑˆĞ¸Ñ‚ÑŒ ÑÑ‚Ñƒ ÑÑ‚Ñ€Ğ°Ğ½Ğ¸Ñ†Ñƒ"
"id":
  footer_os: "Situs ini bersifat open source."
  footer_im: "Perbaiki halaman ini"
